### ISSUE TITLE
Server doesn't work

### ISSUE THREAD

**Issue by brunocascio** [kennedyoliveira/jetbrains-teamcity-docker#1]
I'm trying to run following the documentation, but after run `docker-compose up -d` I got this error:

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.19.0.4	429fd785dd4a
Starting TeamCity Server 10.0...
Invalid layout of java.lang.Thread at name
Error occurred during initialization of VM
Invalid layout of preloaded class: use -XX:+TraceClassLoading to see the origin of the problem class
```

**Comment by kennedyoliveira** [comment]
Hey @brunocascio, thanks for the feedback!
I'm checking and look something is happening on the base image, i'm changing it to a image that i built and use, so it's working, and in a moment i'll update with some fixes, and the most recent teamcity, 10.0.4

**Comment by brunocascio** [comment]
Thanks for the quickly response @kennedyoliveira :dancer:

**Comment by kennedyoliveira** [comment]
@brunocascio, took me a while because changing the base image resulted in some weird SSL errors, but now everything is fixed, i just updated the images, docker is build, you can wait to download to new image or clone the repository/pull new changes and run `docker-compose build`.

Waiting on your feedback

**Comment by kennedyoliveira** [comment]
By the way, updated to version `10.0.4` was on `10.0.0`

**Comment by brunocascio** [comment]
@kennedyoliveira Awesome! I'm going to check this now.

**Comment by brunocascio** [comment]
Yes, it works :dancer: 

Thanks!!

**Comment by kennedyoliveira** [comment]
@brunocascio your welcome :D
